project:
  type: website
  resources:
    - "cv.pdf"

website:
  title: "Alexandre Bohyn"
  favicon: /img/favicon.png
  navbar:
    left:
      - text: "Publications"
        href: publications.qmd
      - text: "Talks"
        href: presentations.qmd
      - text: "CV"
        href: cv.qmd

format:
  html:
    theme: simplex
    css: styles.css

execute: 
  freeze: auto


