project:
  type: website

website:
  title: "Alexandre Bohyn"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Presentations"
        href: presentations.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

execute: 
  freeze: auto


