project:
  type: website
  resources:
    - "cv.pdf"

website:
  title: "Alexandre Bohyn"
  favicon: /img/icon.png
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Presentations"
        href: presentations.qmd
      - text: "Publications"
        href: publications.qmd
      # - text: "Projects"
      #   href: projects.qmd
      

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

execute: 
  freeze: auto


